"""empty message

Revision ID: 538d3a56137a
Revises: f994ecb62b83
Create Date: 2026-08-31 15:01:15.794438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '538d3a56137a'
down_revision = 'f994ecb62b83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('senha', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuario')
    # ### end Alembic commands ###
