"""empty message

Revision ID: 939102426da0
Revises: a5d9a9571f35
Create Date: 2026-08-20 22:01:04.284782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '939102426da0'
down_revision = 'a5d9a9571f35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('curso', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'formacao', ['formacao_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('curso', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
