"""empty message

Revision ID: d3d434109bf7
Revises: 286bb3a09802
Create Date: 2026-08-20 02:23:39.524817

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd3d434109bf7'
down_revision = '286bb3a09802'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('curso', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nome', sa.String(length=100), nullable=False))
        batch_op.drop_column('titulo')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('curso', schema=None) as batch_op:
        batch_op.add_column(sa.Column('titulo', mysql.VARCHAR(length=100), nullable=False))
        batch_op.drop_column('nome')

    # ### end Alembic commands ###
